import type { DatabaseSchema } from "./database"

// Dados mockados baseados no JSON fornecido
export const mockData: DatabaseSchema = {
  Iniciativas: [
    {
      Alcance: "",
      Descrição:
        "Canais e produtos voltados a levar evidências científicas para formuladores de políticas e agentes de implementação que atuam para aterrissar as políticas públicas e para desenvolver serviços públicos para as crianças na primeira infância.",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "NCPI Dissemina",
      LÍDER: "",
      "O que é":
        "O NCPI Dissemina é a iniciativa voltada a ampliar a capacidade do NCPI disseminar evidências e conhecimentos científicos plurais com potencial de impacto sobre o desenho e a implementação de políticas públicas voltadas às Primeiras Infâncias.",
      OBSERVAÇÕES: "",
      Porta: "Porta para fora",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "78",
              ENCAMINHAMENTO: "Revisar estratégia de SEO para melhorar posicionamento",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "Manter o site do NCPI entre os 3 primeiros colocados no Google em buscas de expressões prioritárias",
              OBSERVAÇÕES:
                "O site do NCPI tem mantido bom posicionamento nas buscas por palavras-chave prioritárias, mas ainda há oportunidades de melhoria para alcançar o primeiro lugar em algumas expressões específicas.",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "37",
              ENCAMINHAMENTO: "Mapear novos especialistas em regiões sub-representadas",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Aumentar a diversidade étnico-racial e regional de fontes sugeridas para entrevistas a veículos Tier 1",
              OBSERVAÇÕES:
                "Houve avanço na diversidade de fontes, mas ainda estamos abaixo da meta estabelecida. É necessário ampliar o banco de especialistas e intensificar o contato com pesquisadores de diferentes regiões do país.",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "19",
              ENCAMINHAMENTO: "Agendar reuniões com editores de veículos prioritários",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Obter espaço editorial fixo para ao menos 2 integrantes do CC, com diversidade étnico-racial, regional e epistemológica",
              OBSERVAÇÕES:
                "Meta em situação crítica. Apenas um espaço editorial foi conquistado até o momento, e não há negociações avançadas com outros veículos. É necessário revisar a estratégia e intensificar contatos com editores.",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "Documentar estratégias bem-sucedidas para replicação",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "Aumentar base de inscrições na newsletter em X% ao ano com taxa média de abertura de 20% ao ano",
              OBSERVAÇÕES:
                "Meta concluída com sucesso. A base de inscritos cresceu acima do esperado e a taxa de abertura se manteve em 23%, superando a meta de 20%. As estratégias de conteúdo e segmentação mostraram-se eficazes.",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "Contratar serviço de clipping e monitoramento de mídia",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "X% de crescimento de menções ao NCPI e seus produtos na imprensa",
              OBSERVAÇÕES:
                "Meta ainda não monitorada. É necessário implementar ferramentas de monitoramento de mídia para acompanhar as menções ao NCPI e seus produtos na imprensa.",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "NCPI visto como top referência sobre evidências para desenho e implementação de PPPI",
        },
        {
          Metas: [
            {
              Alcance: "65",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "12 produtos derivados do CC ao longo dos 3 anos",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "10 produtos derivados do Prêmio",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "45",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "8 produtos derivados do Simpósio",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "25",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "6 encontros de disseminação com Comunidade NCPI (3 online e 3 presenciais)",
              OBSERVAÇÕES: "Atraso no cronograma",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "70",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "Participação de pesquisadores e/ou distribuição de materiais em ao menos 2 eventos estratégicos por ano",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Públicos prioritários com acesso a informação atualizada e útil sobre implementação de PPPI",
        },
      ],
    },
    {
      Alcance: "",
      Descrição:
        "Encontro que apresenta evidências científicas e boas práticas capazes de pautar o debate público sobre políticas públicas para as primeiras infâncias, considerando a diversidade brasileira com vistas a contribuir para a tomada de decisão de gestores públicos.",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "Simpósio Internacional",
      LÍDER: "",
      "O que é":
        "O Simpósio é evento voltado à sensibilização de gestores públicos, lideranças da sociedade civil e da academia por meio de evidências para a qualificação da implementação de políticas públicas de primeira infância considerando a diversidade étnico-racial, regional e socioeconômica do país.",
      OBSERVAÇÕES: "",
      Porta: "Porta para fora",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "80",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "80% dos Participantes afirmam que participar do Simpósio ampliou seus conhecimentos sobre Pi e suas conexões com atores do campo",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "1 encontro da Comunidade NCPI por edição do Simpósio",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "40",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Ao menos 5 side events por edição",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "20",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Participação de 3 a 5 palestrantes internacionais, com 50% deles com origem no Sul Global",
              OBSERVAÇÕES: "Dificuldade em atrair palestrantes",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "Ao menos 1 estudo científico inédito lançado no Simpósio",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Simpósio como espaço agregador das principais pautas e tendências de implementação de PPPI",
        },
        {
          Metas: [
            {
              Alcance: "85",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "100% dos estados brasileiros com participantes presencial e/ou on-line",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "30% do público advindo do N ou NE, sendo pretos, pardos e indígenas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "50",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "300 participantes presenciais e ao menos 1000 online",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "30",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "50% de participantes advindos da academia, OSC e imprensa",
              OBSERVAÇÕES: "Meta abaixo do esperado",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "75",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "50% de gestores públicos de alto e médio escalão + nível de rua",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "40% dos palestrantes entre pessoas pretas, pardas e indígenas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado:
            "Perfil de palestrantes e participantes orientado pelas diversidades regional e étnico-racial brasileiras",
        },
      ],
    },
    {
      Alcance: "",
      Descrição:
        "Premiação que identifica e reconhece pesquisadores relacionados às primeiras infâncias, visando fortalecer a produção, disseminação e uso de evidências para apoiar a formulação e qualificação de políticas públicas em primeira infância no Brasil.",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "Prêmio",
      LÍDER: "",
      "O que é":
        "O Prêmio identifica e reconhece pesquisadores que abordam as múltiplas infâncias e desigualdades nas primeiras infâncias brasileiras. A iniciativa busca promover e disseminar conhecimento científico, apoiando a formulação e a implementação de políticas públicas para a primeira infância no Brasil.",
      OBSERVAÇÕES: "",
      Porta: "Porta para fora",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "70",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "50% de participantes do N e NE em todas as etapas de cada edição",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "50% de participantes pretos, pardos e indígenas em todas as etapas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "55",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Pesquisas distribuídas pelas diferentes área de concentração",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "25",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Assegurar ao menos 5 parceiros divulgadores a cada edição: FNP, RNPI, CNM, CPAPI, etc.",
              OBSERVAÇÕES: "Faltam 2 parceiros",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "50% da comissão julgadora do Prêmio formada por preto, pardos e indígenas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Todas as etapas da premiação com garantia de diversidade epistêmica, geográfica e racial",
        },
        {
          Metas: [
            {
              Alcance: "80",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "1 formação em comunicação e influência para todos os finalistas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "1 formação em aplicação de evidências às PP para os premiados",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "40",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "50 gestores públicos e de OSC presentes na cerimônia de premiação",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "30",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Ao menos 50% das pesquisas inscritas voltadas às crianças pretas, pardas e indígenas",
              OBSERVAÇÕES: "Apenas 30% atingido",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Pesquisas premiadas articuladas com a gestão pública e inserção na imprensa",
        },
      ],
    },
    {
      Alcance: "",
      Descrição:
        "Formação para sensibilizar, mobilizar e capacitar lideranças de alto nível para qualificar a elaboração e implementação de políticas, programas e ações voltados ao desenvolvimento das primeiras infâncias no Brasil.",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "ELP",
      LÍDER: "",
      "O que é":
        "A formação executiva, desenvolvida em parceria com a Escola de Saúde Pública da Universidade Harvard, busca mobilizar e capacitar lideranças para qualificar a criação e implementação de políticas, programas e ações públicas voltados ao desenvolvimento das múltiplas primeiras infâncias brasileiras.",
      OBSERVAÇÕES: "",
      Porta: "Porta para fora",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "85",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "80% dos participantes avaliam seus argumentos e evidências sobre PI como excelente/bom",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "80% dos participantes avaliam suas habilidades de mobilizar agentes a favor da PI como excelente/bom",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "60",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "80% dos participantes avaliam seu conhecimento para implementar políticas públicas de PI como excelente/bom",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "85",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "NPS do Programa acima de 90%",
              OBSERVAÇÕES: "NPS atual: 85%",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "90% dos plano de ação apresentados com recortes das múltiplas infâncias brasileiras",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "75",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "Ao menos 70% dos planos de ação em algum estágio de implementação",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado:
            "Lideranças sensibilizadas e engajadas a implementar PP voltadas às múltiplas infâncias brasileiras",
        },
        {
          Metas: [
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "Mínimo de 40% dos participantes pretos, pardos e indígenas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "45",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Assegurar ao menos 15% de participantes para as 5 regiões brasileiras",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "30",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "40% de diversidade nos professores de todas as etapas",
              OBSERVAÇÕES: "Apenas 30% atingido",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "65",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "Ao menos 50% dos participantes ocupam posições de liderança na gestão pública",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Participantes e docentes pretos, pardos e indígenas presentes de modo significativo no ELP",
        },
      ],
    },
    {
      Alcance: "",
      Descrição: "",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "MOBILIZAÇÃO E GESTÃO DE RECURSOS FINANCEIROS",
      LÍDER: "",
      "O que é":
        "Iniciativa responsável pela captação e gestão de recursos financeiros para garantir a sustentabilidade das ações do NCPI.",
      OBSERVAÇÕES: "",
      Porta: "Porta para dentro",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "100% dos grants previstos, aprovados com os parceiros",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "Prospecção de ao menos 1 parceiro para a fase 6.",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Fases V e VI financiadas, com novos parceiros que fortaleçam a coalizão e as iniciativas",
        },
        {
          Metas: [
            {
              Alcance: "60",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "100% dos relatórios financeiros aprovados pelos parceiros",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "35",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "100% dos compromissos financeiros executados",
              OBSERVAÇÕES: "Atraso nos pagamentos",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "Acompanhamento mensal do orçamento realizado pela equipe",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Gestão financeira precisa, eficiente e transparente assegurada ao longo da Fase V",
        },
      ],
    },
    {
      Alcance: "",
      Descrição: "",
      ENCAMINHAMENTO: "",
      "FAROL NO TRIMESTRE": "",
      Iniciativas: "GESTÃO DE IMPACTO",
      LÍDER: "",
      "O que é": "Iniciativa responsável pelo monitoramento e avaliação dos resultados e impactos das ações do NCPI.",
      OBSERVAÇÕES: "",
      Porta: "Porta para dentro",
      Resultados: [
        {
          Metas: [
            {
              Alcance: "90",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "100% das reuniões previstas para as instâncias realizadas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "30% do CC e 30% do Comitê Estratégico formado por pretos, pardos e indígenas",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "50",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Plano de Trabalho do comitê científico finalizado e implementado",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "25",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Comitê estratégico com papéis, responsabilidades e rituais definidos e funcionais",
              OBSERVAÇÕES: "Necessário realinhamento",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "0",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Não monitorado",
              LÍDER: "Fernanda Costa",
              Meta: "Parceiros implementadores acompanhados e com feedbacks ao longo de todo a Fase V",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Comitês gestores, executivo e científico implementados com a potência esperada",
        },
        {
          Metas: [
            {
              Alcance: "75",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Satisfatório",
              LÍDER: "Fernanda Costa",
              Meta: "Avaliação da Fase V concluída",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "100",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Concluída",
              LÍDER: "Fernanda Costa",
              Meta: "Aprendizados da Fase V consolidados pelas comitês de governança",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "55",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Alerta",
              LÍDER: "Fernanda Costa",
              Meta: "Plano monitorado pela equipe mensalmente e pelos comitês periodicamente",
              OBSERVAÇÕES: "",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
            {
              Alcance: "20",
              ENCAMINHAMENTO: "",
              "FAROL NO TRIMESTRE": "Crítico",
              LÍDER: "Fernanda Costa",
              Meta: "Plano NCPI Fase 6 desenhado, aprovado e financiado",
              OBSERVAÇÕES: "Atraso no cronograma",
              "Pessoa responsável": "",
              Semestre: "1º 2025",
            },
          ],
          Resultado: "Fase V avaliada de maneira robusta e com aprendizados importantes para a Fase 6",
        },
      ],
    },
  ],
  dashboardData: {
    Iniciativas: [],
  },
  iniciativas: {
    nome: "Nova Iniciativa",
    status: "satisfatório",
  },
  users: {
    "-ONVyPyIlarrXL0FIXkm": {
      email: "joao@example.com",
      fullName: "João Silva",
      password: "$2b$10$cyZTY3Y5Rp1BGtfyjIQsw.xTdVKUGpEz2u5EbWst3/snl2Rr32jcS",
    },
    "-ONW1MGJsGSZCVTlAKbd": {
      email: "anasilva@example.com",
      fullName: "Ana Silva",
      password: "$2b$10$wocXzEl0UCH9HonQ1VSml.4jwdDOxm.1nL4l0ZSq8zh2vuBNvAQPm",
    },
  },
}
